### ISSUE TITLE
A function advice

### ISSUE THREAD

**Issue by cxhttt233** [Hopkins1/TradSimpChinese#14]
Thank you for your plugin. It is really helpful for me.
I have an immature advice that it will be more potent if it can trans multiple e-books at one time.
: When we select multiple e-books and click the plugin in the tools area, all books selected can be changed into the format we need.

**Comment by Hopkins1** [comment]
It looks like this could be done. Would the original book be deleted and then replaced by the modified book? Sounds a little dangerous.

One other way would be to use the command line version on all the files, create a new library to contain them, and then add the modified books to the new library (drag and drop all of them). Maybe the old library would have traditional Chinese and the new library would have simplified.

Using the command line is very easy. There are some examples described on the MobileRead forum.

**Comment by cxhttt233** [comment]
Ok, It seems that the command line version is a better solution. Thanks a lot for your reply.
