### ISSUE TITLE
Version 3.0 has a bug.

### ISSUE THREAD

**Issue by gushiho** [Hopkins1/TradSimpChinese#20]
I use Win 10 + Calibre 6.10.0.
When I install v. 3.0, it cannot convert from simplified (mainland) to traditional (Taiwan) for an epub file.
I uninstalled v. 3.0, reinstalled v. 2.4.0.
It works again.
So, it must be a bug in the new version.
Please see to it.
I used previous version for some time now, and it works wonderfully.
Thank you for making this plugin.

**Comment by Hopkins1** [comment]
More information is needed.

What were the settings?
What was the error mewssage?
Was this via the GUI or the command line?

**Comment by Hopkins1** [comment]
Never mind. I can reproduce it now.
