### ISSUE TITLE
Can we add the vertical reading option?

### ISSUE THREAD

**Issue by ayeteng** [Hopkins1/TradSimpChinese#4]
Hi Hopkins,

Can we add the vertical reading option when do the converting?

2 step:

Add the below lines to CSS:

@font-face {
font-family: unicode-range: U+3100-312F;
}

body{
writing-mode: vertical-rl;
line-break: normal;
-epub-writing-mode: vertical-rl;
-webkit-writing-mode: vertical-rl;
-epub-line-break: normal;
-webkit-line-break: normal;
}

p{
margin: 1.5rem;
}
 
h2{
margin-left:3rem;
margin-top:3rem;
}

Change the ncx (next page in left direction):

`<spine toc="ncx" page-progression-direction="rtl">`

**Comment by Hopkins1** [comment]
I like this idea. It may take a little longer to implement since I need to also change some of the characters  into their vertical form (i.e. 『 ->﹃). I should also add the ability to change vertical text  into horizontal text.

BTW, the Calibre and Sigil book readers do not support vertical text. Users will need to use different software (such as Chrome Readium) to verify vertical books.

**Comment by ayeteng** [comment]
yes it is. I use Chrome Readium to read the vertical text. By far, I add it manually and it works.

**Comment by Hopkins1** [comment]
I've created a new release 2.2.0 that may address this issue.
If creating vertical text, be sure to specify if the reader is Chrome Readium or Amazon Kindle.
Use the Kindle Previewer3 application to convert an epub into a mobi file for use on kindle.

**Comment by ayeteng** [comment]
Thanks! How can I get this update? 2.2.0 is not exist in my Calibre. Shall I install it manually?

**Comment by Hopkins1** [comment]
I found a couple of bugs in the command line processing section, so I had to update the release version. It should soon show up on the Calibre viewer.

**Comment by Hopkins1** [comment]
Fixed under release 2.2.1. If there is a problem with the release, we can reopen the issue.

**Comment by ayeteng** [comment]
Hi Hopkins1,

Found some trouble to use 2.2.1:
1. It takes 4 to 5 times longer if I choose vertical mode.
2. The vertical mode cannot work well if I convert to AZW3 by Calibre then download to Kindle.
=> need to add all 3 lines in body:
writing-mode: vertical-rl;
-epub-writing-mode: vertical-rl;
-webkit-writing-mode: vertical-rl;

Can you revise it? Thanks.
