### ISSUE TITLE
Incomplete vertical conversion in 2.2.1

### ISSUE THREAD

**Issue by ayeteng** [Hopkins1/TradSimpChinese#5]
Hi Hopkins1,

Found some issues to use 2.2.1:

1. It takes 4 to 5 times longer if I choose vertical mode with optimize to Readium or Kindle mode.

2. The vertical mode cannot work well if I convert to AZW3 by Calibre then download to my Kindle PW.
=> need to add all 3 lines in the body:
writing-mode: vertical-rl;
-epub-writing-mode: vertical-rl;
-webkit-writing-mode: vertical-rl;

Can you revise it? Thanks.

**Comment by Hopkins1** [comment]
I've added more CSS file rules which appear to fix the conversion problem.

I don't have a good way to change the code to speed up the conversion of horizontal punctuation to vertical punctuation. Readium optimization is not strictly needed if one is willing to live with it displaying a rotated version of the horizontal punctuation rather than the vertical punctuation. Unfortunately, Kindle does not do this rotation in all cases, so optimization is probably needed.

**Comment by Hopkins1** [comment]
Updated conversion to improve speed when optimizing for Readium and Kindle. See release 2.2.3.
I'll close this issue in a couple of weeks if there are not any problems.

**Comment by ayeteng** [comment]
Thank you very much about your effort. Really appreciate to get such good tool and reduce my time to do it manually.

I convert few books. I found one book cannot follow the page-progression-direction="rtl" in my Kindle PW. I see this setting exist in the opf file but I cannot find the reason. I am trying to compare what's wrong there and will update soon.

2nd, I notices one thing, if there exist the body setting, the relevant setting will set in one body:
body {
  -epub-writing-mode: vertical-rl;
  writing-mode: vertical-rl;
  -webkit-writing-mode: vertical-rl;
  line-break: normal;
  webkit-line-break: normal;
}

But if there is no body setting, it will appear as below:
body {
  writing-mode: vertical-rl;
}
body {
  -epub-writing-mode: vertical-rl;
}
body {
  -webkit-writing-mode: vertical-rl;
}
body {
  line-break: normal;
}
body {
  webkit-line-break: normal;
}

Not sure if it affect any css setting.

3rd, I notices the tool will add the ';' at the end of each line in css file. Is it necessary?

**Comment by Hopkins1** [comment]
I see what is causing the multiple body problem. I'll fix that in the next release.

The addition of the ';' is being done automatically by the cssutils package. I don't think it is a problem, but I will investigate.

**Comment by ayeteng** [comment]
according to http://help.dottoro.com/lcfqiqfq.php
Please correct the "webkit-line-break" to "-webkit-line-break" (with the '-' in the front)
Thank you.

**Comment by Hopkins1** [comment]
Everything has been added and a new release issued. 

The newline added after every CSS rule is part of the cssutils package. I don't see any way to change it. Since it does not affect functionality and it improves readability, I'm not going to look any further into changing it.

Thanks!
