### ISSUE TITLE
any good idea to do the convert by CLI not through Calibre?

### ISSUE THREAD

**Issue by ayeteng** [Hopkins1/TradSimpChinese#8]
Hi all,

Is there any good instruction to convert the books by command line command instead of run the plugin in the Calibre? I have 20+ books to convert and expect to get a better/easy way to do it by script.

**Comment by ayeteng** [comment]
I found it.

Thanks.

Command Line Interface(CLI)
Details:

Spoiler: 
Example: overwrite all ebook files in a directory from Mainland simplified into Taiwan traditional (also change to East Asian quote marks and vertical text orientation) add in a "V" suffix to the file name and optimizing for display on the Chrome Readium reader:
calibre-debug --run-plugin "Chinese Text Conversion" -- -ol tw -il cn -d s2t -od out -qt e -td v -tdo r -a V *.epub *.azw3
Example: overwrite all epub files in a directory from Taiwan traditional into Mainland simplified, but don't actually perform the write. Just print what would happen:
calibre-debug --run-plugin "Chinese Text Conversion" -- -ol cn -il tw -d t2s -t my_chinese_epub_dir/*.epub
Code:
usage: calibre-debug --run-plugin "Chinese Text Conversion" -- [-h] [-il {cn,hk,tw}] [-ol {cn,hk,tw}]
[-d {t2s,s2t,t2t,none}] [-p] [-qt {w,e,no_change}]
[-sq] [-td {h,v,no_change}] [-tdo {r,k,none}] [-v]
[-t] [-q] [-od OUTDIR_OPT] [-a APPEND_SUFFIX_OPT]
[-f] [-s]
ebook-filepath [ebook-filepath ...]

Convert Chinese characters between traditional/simplified types and/or change
text style. Plugin Version: 2.3.0

positional arguments:
  ebook-filepath         One or more ebook filepaths - UNIX style wildcards
                        accepted

optional arguments:
  -h, --help            show this help message and exit
  -il {cn,hk,tw}, --input-locale {cn,hk,tw}
                        Set to the epub origin locale if known (Default: cn)
  -ol {cn,hk,tw}, --output-locale {cn,hk,tw}
                        Set to the epub target locale (Default: cn)
  -d {t2s,s2t,t2t,none}, --direction {t2s,s2t,t2t,none}
                        Set to the epub conversion direction (Default: none)
  -p, --phrase_convert  Convert phrases to target locale versions (Default:
                        False)
  -qt {w,e,no_change}, --quotation-type {w,e,no_change}
                        Set to the epub origin locale if known (Default:
                        no_change)
  -sq, --smart_quotes   Use smart quotes if applicable (Default: False)
  -td {h,v,no_change}, --text-direction {h,v,no_change}
                        Set to the epub origin locale if known (Default:
                        no_change)
  -tdo {r,k,none}, --text-device-optimize {r,k,none}
                        Optimize text for device (Default: none)
  -v, --verbose         Print out details as the conversion progresses
                        (Default: False)
  -t, --test            Run conversion operations without saving results
                        (Default: False)
  -q, --quiet           Do not print anything, ignore warnings - this option
                        overides the -s option (Default: False)
  -od OUTDIR_OPT, --output-dir OUTDIR_OPT
                        Set to the epub output file directory (Default:
                        overwrite existing epub file)
  -a APPEND_SUFFIX_OPT, --append_suffix APPEND_SUFFIX_OPT
                        Append a suffix to the output file basename (Default:
                        )
  -f, --force           Force processing by ignoring warnings (e.g. allow
                        overwriting files with no prompt)
  -s, --show            Show the settings based on user cmdline options and
                        exit (Default: False)

**Comment by Hopkins1** [comment]
Note: I've made a slight wording change to the command line usage for the -qt option, but the operational code is not changed.

I think this is the command line you may want if all of the files you have are Simplified Chinese and are all in one directory. It will take all of the files and convert them to Taiwan traditional, East Asian quotes, optimized for Readium, and create new files with the same name except the letter "T" is appended.

Copy and paste the following:

calibre-debug --run-plugin "Chinese Text Conversion" -- -ol tw -il cn -d s2t -qt e -td v -tdo r -a T *.epub
